const crypto = require('crypto');
const jwt = require('jsonwebtoken');
const {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  GOOGLE_ENABLED,
  GOOGLE_ALLOWED_DOMAINS
} = require('../config/env');

/**
 * Google sign-in over the server-side authorization-code flow.
 *
 * Implemented against Google's endpoints directly rather than pulling in
 * google-auth-library, matching the in-repo cookie parser: the flow needs three
 * HTTP calls and one JWT verification, all of which Node 20 covers natively.
 *
 * Defence in depth on the callback:
 *   - `state`  round-trips through an httpOnly cookie to stop CSRF on the callback
 *   - `nonce`  is embedded in the id_token by Google and checked on return, so a
 *              token minted for another session cannot be replayed into this one
 *   - the id_token signature is verified against Google's published JWKS
 */

const AUTH_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth';
const TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token';
const JWKS_URI = 'https://www.googleapis.com/oauth2/v3/certs';
const VALID_ISSUERS = ['https://accounts.google.com', 'accounts.google.com'];

/** Google rotates signing keys slowly; caching avoids a fetch per sign-in. */
let jwksCache = { keys: null, fetchedAt: 0 };
const JWKS_TTL_MS = 60 * 60 * 1000;

async function getSigningKey(kid) {
  const isStale = !jwksCache.keys || Date.now() - jwksCache.fetchedAt > JWKS_TTL_MS;

  if (isStale) {
    const response = await fetch(JWKS_URI);
    if (!response.ok) throw new Error(`Could not fetch Google signing keys (${response.status})`);
    const body = await response.json();
    jwksCache = { keys: body.keys || [], fetchedAt: Date.now() };
  }

  let jwk = jwksCache.keys.find((k) => k.kid === kid);

  // An unknown kid usually means the keys rotated since we cached them.
  if (!jwk && Date.now() - jwksCache.fetchedAt > 60 * 1000) {
    jwksCache = { keys: null, fetchedAt: 0 };
    return getSigningKey(kid);
  }

  if (!jwk) throw new Error('Google id_token was signed with an unrecognised key');
  return crypto.createPublicKey({ key: jwk, format: 'jwk' });
}

/** Random, URL-safe value used for both the state and the nonce. */
function randomToken() {
  return crypto.randomBytes(32).toString('base64url');
}

/**
 * Builds the consent-screen URL. `state` and `nonce` are generated by the
 * caller so it can persist them in cookies before redirecting.
 */
function buildAuthUrl({ state, nonce, prompt = 'select_account' }) {
  if (!GOOGLE_ENABLED) throw new Error('Google sign-in is not configured');

  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    redirect_uri: GOOGLE_CALLBACK_URL,
    response_type: 'code',
    scope: 'openid email profile',
    state,
    nonce,
    prompt,
    // We only need identity, so no refresh token from Google is requested.
    access_type: 'online',
    include_granted_scopes: 'true'
  });

  return `${AUTH_ENDPOINT}?${params.toString()}`;
}

/** Trades the one-time authorization code for Google's id_token. */
async function exchangeCode(code) {
  const response = await fetch(TOKEN_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      code,
      client_id: GOOGLE_CLIENT_ID,
      client_secret: GOOGLE_CLIENT_SECRET,
      redirect_uri: GOOGLE_CALLBACK_URL,
      grant_type: 'authorization_code'
    })
  });

  const payload = await response.json().catch(() => ({}));

  if (!response.ok) {
    throw new Error(payload.error_description || payload.error || 'Google rejected the authorization code');
  }
  if (!payload.id_token) throw new Error('Google did not return an id_token');

  return payload.id_token;
}

/** Verifies signature, issuer, audience and expiry, then checks the nonce. */
async function verifyIdToken(idToken, expectedNonce) {
  const decoded = jwt.decode(idToken, { complete: true });
  if (!decoded || !decoded.header || !decoded.header.kid) {
    throw new Error('Google id_token is malformed');
  }

  const key = await getSigningKey(decoded.header.kid);

  const claims = jwt.verify(idToken, key, {
    algorithms: ['RS256'],
    audience: GOOGLE_CLIENT_ID,
    issuer: VALID_ISSUERS
  });

  if (!expectedNonce || claims.nonce !== expectedNonce) {
    throw new Error('Google id_token nonce did not match this sign-in attempt');
  }
  if (!claims.email) throw new Error('Google account did not expose an email address');
  if (claims.email_verified === false) {
    throw new Error('This Google account has an unverified email address');
  }

  return {
    googleId: claims.sub,
    email: String(claims.email).toLowerCase(),
    emailVerified: claims.email_verified !== false,
    displayName: claims.name || String(claims.email).split('@')[0],
    avatarUrl: claims.picture || undefined,
    hostedDomain: claims.hd ? String(claims.hd).toLowerCase() : null
  };
}

/**
 * Domain allowlist. Empty config means any Google account is acceptable; set
 * GOOGLE_ALLOWED_DOMAINS to restrict self-registration to official domains.
 */
function isDomainAllowed(email, hostedDomain) {
  if (!GOOGLE_ALLOWED_DOMAINS.length) return true;
  const domain = (hostedDomain || String(email).split('@')[1] || '').toLowerCase();
  return GOOGLE_ALLOWED_DOMAINS.includes(domain);
}

module.exports = {
  randomToken,
  buildAuthUrl,
  exchangeCode,
  verifyIdToken,
  isDomainAllowed
};
